const FLASHCARDS = [
  // --- ПРИВЕТСТВИЯ ---
  { sr: "Dobar dan.",       ru: "Добрый день.",                category: "greetings" },
  { sr: "Dobro jutro.",     ru: "Доброе утро.",                category: "greetings" },
  { sr: "Dobro veče.",      ru: "Добрый вечер.",               category: "greetings" },
  { sr: "Zdravo.",          ru: "Привет / Здравствуй.",        category: "greetings" },
  { sr: "Ćao.",             ru: "Пока / Привет.",              category: "greetings" },
  { sr: "Doviđenja.",       ru: "До свидания.",                category: "greetings" },
  { sr: "Laku noć.",        ru: "Спокойной ночи.",             category: "greetings" },
  { sr: "Vidimo se.",       ru: "Увидимся.",                   category: "greetings" },
  { sr: "Kako si?",         ru: "Как ты?",                    category: "greetings" },
  { sr: "Kako ste?",        ru: "Как вы?",                    category: "greetings" },
  { sr: "Dobro sam.",       ru: "Я хорошо.",                  category: "greetings" },
  { sr: "Odlično.",         ru: "Отлично.",                   category: "greetings" },
  { sr: "Nije loše.",       ru: "Неплохо.",                   category: "greetings" },
  { sr: "Drago mi je.",     ru: "Приятно познакомиться.",      category: "greetings" },
  { sr: "Hvala.",           ru: "Спасибо.",                   category: "greetings" },
  { sr: "Molim.",           ru: "Пожалуйста.",                category: "greetings" },
  { sr: "Izvinite.",        ru: "Извините.",                  category: "greetings" },
  { sr: "Nema problema.",   ru: "Нет проблем.",               category: "greetings" },
  { sr: "U redu.",          ru: "Хорошо. / Ладно.",           category: "greetings" },
  { sr: "Naravno.",         ru: "Конечно.",                   category: "greetings" },

  // --- ЧИСЛА ---
  { sr: "jedan / jedna",  ru: "один / одна",    category: "numbers" },
  { sr: "dva / dve",      ru: "два / две",      category: "numbers" },
  { sr: "tri",            ru: "три",            category: "numbers" },
  { sr: "četiri",         ru: "четыре",         category: "numbers" },
  { sr: "pet",            ru: "пять",           category: "numbers" },
  { sr: "šest",           ru: "шесть",          category: "numbers" },
  { sr: "sedam",          ru: "семь",           category: "numbers" },
  { sr: "osam",           ru: "восемь",         category: "numbers" },
  { sr: "devet",          ru: "девять",         category: "numbers" },
  { sr: "deset",          ru: "десять",         category: "numbers" },
  { sr: "jedanaest",      ru: "одиннадцать",    category: "numbers" },
  { sr: "dvanaest",       ru: "двенадцать",     category: "numbers" },
  { sr: "dvadeset",       ru: "двадцать",       category: "numbers" },
  { sr: "trideset",       ru: "тридцать",       category: "numbers" },
  { sr: "sto",            ru: "сто",            category: "numbers" },
  { sr: "hiljada",        ru: "тысяча",         category: "numbers" },

  // --- ЕДА ---
  { sr: "hleb",       ru: "хлеб",         category: "food" },
  { sr: "meso",       ru: "мясо",         category: "food" },
  { sr: "riba",       ru: "рыба",         category: "food" },
  { sr: "povrće",     ru: "овощи",        category: "food" },
  { sr: "voće",       ru: "фрукты",       category: "food" },
  { sr: "jabuka",     ru: "яблоко",       category: "food" },
  { sr: "paradajz",   ru: "помидор",      category: "food" },
  { sr: "krompir",    ru: "картофель",    category: "food" },
  { sr: "jaje",       ru: "яйцо",         category: "food" },
  { sr: "sir",        ru: "сыр",          category: "food" },
  { sr: "mleko",      ru: "молоко",       category: "food" },
  { sr: "supa",       ru: "суп",          category: "food" },
  { sr: "ćevapčić",  ru: "чевапчич",     category: "food" },
  { sr: "torta",      ru: "торт",         category: "food" },
  { sr: "voda",       ru: "вода",         category: "food" },
  { sr: "kafa",       ru: "кофе",         category: "food" },
  { sr: "čaj",        ru: "чай",          category: "food" },
  { sr: "vino",       ru: "вино",         category: "food" },
  { sr: "pivo",       ru: "пиво",         category: "food" },
  { sr: "sok",        ru: "сок",          category: "food" },
  { sr: "doručak",    ru: "завтрак",      category: "food" },
  { sr: "ručak",      ru: "обед",         category: "food" },
  { sr: "večera",     ru: "ужин",         category: "food" },
  { sr: "račun",      ru: "счёт",         category: "food" },

  // --- СЕМЬЯ ---
  { sr: "porodica",    ru: "семья",           category: "family" },
  { sr: "mama / majka", ru: "мама / мать",    category: "family" },
  { sr: "tata / otac", ru: "папа / отец",     category: "family" },
  { sr: "brat",        ru: "брат",            category: "family" },
  { sr: "sestra",      ru: "сестра",          category: "family" },
  { sr: "sin",         ru: "сын",             category: "family" },
  { sr: "ćerka",       ru: "дочь",            category: "family" },
  { sr: "muž",         ru: "муж",             category: "family" },
  { sr: "žena",        ru: "жена / женщина",  category: "family" },
  { sr: "dete",        ru: "ребёнок",         category: "family" },
  { sr: "baka",        ru: "бабушка",         category: "family" },
  { sr: "deda",        ru: "дедушка",         category: "family" },
  { sr: "kolega",      ru: "коллега",         category: "family" },
  { sr: "komšija",     ru: "сосед",           category: "family" },
  { sr: "drug",        ru: "друг",            category: "family" },

  // --- ГОРОД ---
  { sr: "grad",        ru: "город",              category: "city" },
  { sr: "ulica",       ru: "улица",              category: "city" },
  { sr: "trg",         ru: "площадь",            category: "city" },
  { sr: "park",        ru: "парк",               category: "city" },
  { sr: "restoran",    ru: "ресторан",            category: "city" },
  { sr: "kafić",       ru: "кафе",               category: "city" },
  { sr: "muzej",       ru: "музей",              category: "city" },
  { sr: "pozorište",   ru: "театр",              category: "city" },
  { sr: "bioskop",     ru: "кинотеатр",          category: "city" },
  { sr: "banka",       ru: "банк",               category: "city" },
  { sr: "pošta",       ru: "почта",              category: "city" },
  { sr: "prodavnica",  ru: "магазин",            category: "city" },
  { sr: "aerodrom",    ru: "аэропорт",           category: "city" },
  { sr: "pravo",       ru: "прямо",              category: "city" },
  { sr: "levo",        ru: "налево",             category: "city" },
  { sr: "desno",       ru: "направо",            category: "city" },
  { sr: "blizu",       ru: "рядом / близко",     category: "city" },
  { sr: "daleko",      ru: "далеко",             category: "city" },
  { sr: "Gde je...?",  ru: "Где находится...?",  category: "city" },

  // --- ПУТЕШЕСТВИЯ ---
  { sr: "putovanje",   ru: "путешествие",        category: "travel" },
  { sr: "odmor",       ru: "отдых / отпуск",     category: "travel" },
  { sr: "pasoš",       ru: "паспорт",            category: "travel" },
  { sr: "viza",        ru: "виза",               category: "travel" },
  { sr: "karta",       ru: "билет / карта",      category: "travel" },
  { sr: "kofer",       ru: "чемодан",            category: "travel" },
  { sr: "avion",       ru: "самолёт",            category: "travel" },
  { sr: "voz",         ru: "поезд",              category: "travel" },
  { sr: "autobus",     ru: "автобус",            category: "travel" },
  { sr: "brod",        ru: "корабль",            category: "travel" },
  { sr: "hotel",       ru: "гостиница / отель",  category: "travel" },
  { sr: "rezervacija", ru: "бронирование",       category: "travel" },
  { sr: "Koliko košta?", ru: "Сколько стоит?",   category: "travel" },

  // --- ПОГОДА ---
  { sr: "vreme",      ru: "погода",        category: "weather" },
  { sr: "sunce",      ru: "солнце",        category: "weather" },
  { sr: "kiša",       ru: "дождь",         category: "weather" },
  { sr: "sneg",       ru: "снег",          category: "weather" },
  { sr: "vetar",      ru: "ветер",         category: "weather" },
  { sr: "oblak",      ru: "облако",        category: "weather" },
  { sr: "magla",      ru: "туман",         category: "weather" },
  { sr: "toplo",      ru: "тепло",         category: "weather" },
  { sr: "hladno",     ru: "холодно",       category: "weather" },
  { sr: "sunčano",    ru: "солнечно",      category: "weather" },
  { sr: "oblačno",    ru: "облачно",       category: "weather" },
  { sr: "proleće",    ru: "весна",         category: "weather" },
  { sr: "leto",       ru: "лето",          category: "weather" },
  { sr: "jesen",      ru: "осень",         category: "weather" },
  { sr: "zima",       ru: "зима",          category: "weather" },

  // --- ОДЕЖДА ---
  { sr: "odeća",      ru: "одежда",     category: "clothes" },
  { sr: "haljina",    ru: "платье",     category: "clothes" },
  { sr: "suknja",     ru: "юбка",       category: "clothes" },
  { sr: "pantalone",  ru: "брюки",      category: "clothes" },
  { sr: "majica",     ru: "футболка",   category: "clothes" },
  { sr: "košulja",    ru: "рубашка",    category: "clothes" },
  { sr: "kaput",      ru: "пальто",     category: "clothes" },
  { sr: "jakna",      ru: "куртка",     category: "clothes" },
  { sr: "džemper",    ru: "свитер",     category: "clothes" },
  { sr: "cipele",     ru: "туфли",      category: "clothes" },
  { sr: "patike",     ru: "кроссовки",  category: "clothes" },
  { sr: "čizme",      ru: "сапоги",     category: "clothes" },
  { sr: "šešir",      ru: "шляпа",      category: "clothes" },
  { sr: "šal",        ru: "шарф",       category: "clothes" },
  { sr: "crn",        ru: "чёрный",     category: "clothes" },
  { sr: "beo",        ru: "белый",      category: "clothes" },
  { sr: "crven",      ru: "красный",    category: "clothes" },
  { sr: "plav",       ru: "синий",      category: "clothes" },
  { sr: "zelen",      ru: "зелёный",    category: "clothes" },
  { sr: "žut",        ru: "жёлтый",     category: "clothes" },

  // --- ДОМ ---
  { sr: "stan",          ru: "квартира",          category: "home" },
  { sr: "kuća",          ru: "дом",               category: "home" },
  { sr: "soba",          ru: "комната",           category: "home" },
  { sr: "dnevna soba",   ru: "гостиная",          category: "home" },
  { sr: "spavaća soba",  ru: "спальня",           category: "home" },
  { sr: "kuhinja",       ru: "кухня",             category: "home" },
  { sr: "kupatilo",      ru: "ванная",            category: "home" },
  { sr: "kauč",          ru: "диван",             category: "home" },
  { sr: "sto",           ru: "стол",              category: "home" },
  { sr: "stolica",       ru: "стул",              category: "home" },
  { sr: "krevet",        ru: "кровать",           category: "home" },
  { sr: "orman",         ru: "шкаф",              category: "home" },
  { sr: "prozor",        ru: "окно",              category: "home" },
  { sr: "vrata",         ru: "дверь",             category: "home" },
  { sr: "frižider",      ru: "холодильник",       category: "home" },
  { sr: "televizor",     ru: "телевизор",         category: "home" },

  // --- ГЛАГОЛЫ ---
  { sr: "govoriti",      ru: "говорить",             category: "verbs" },
  { sr: "razumeti",      ru: "понимать",             category: "verbs" },
  { sr: "učiti",         ru: "учить / учиться",      category: "verbs" },
  { sr: "raditi",        ru: "работать",             category: "verbs" },
  { sr: "živeti",        ru: "жить",                 category: "verbs" },
  { sr: "voleti",        ru: "любить / нравиться",   category: "verbs" },
  { sr: "ići",           ru: "идти",                 category: "verbs" },
  { sr: "jesti",         ru: "есть (кушать)",        category: "verbs" },
  { sr: "piti",          ru: "пить",                 category: "verbs" },
  { sr: "čitati",        ru: "читать",               category: "verbs" },
  { sr: "gledati",       ru: "смотреть",             category: "verbs" },
  { sr: "slušati",       ru: "слушать",              category: "verbs" },
  { sr: "kuvati",        ru: "готовить (еду)",       category: "verbs" },
  { sr: "kupovati",      ru: "покупать",             category: "verbs" },
  { sr: "spavati",       ru: "спать",                category: "verbs" },
  { sr: "morati",        ru: "быть должным / нужно", category: "verbs" },
  { sr: "moći",          ru: "мочь",                 category: "verbs" },
  { sr: "hteti",         ru: "хотеть",               category: "verbs" },
  { sr: "planirati",     ru: "планировать",          category: "verbs" },
  { sr: "rezervisati",   ru: "бронировать",          category: "verbs" },

  // --- ПРОФЕССИИ ---
  { sr: "lekar",        ru: "врач",             category: "jobs" },
  { sr: "profesor",     ru: "преподаватель",    category: "jobs" },
  { sr: "student",      ru: "студент",          category: "jobs" },
  { sr: "novinar",      ru: "журналист",        category: "jobs" },
  { sr: "inženjer",     ru: "инженер",          category: "jobs" },
  { sr: "kuvar",        ru: "повар",            category: "jobs" },
  { sr: "konobar",      ru: "официант",         category: "jobs" },
  { sr: "policajac",    ru: "полицейский",      category: "jobs" },
  { sr: "vatrogasac",   ru: "пожарный",         category: "jobs" },
  { sr: "glumac",       ru: "актёр",            category: "jobs" },
  { sr: "pevač",        ru: "певец",            category: "jobs" },
  { sr: "direktor",     ru: "директор",         category: "jobs" },
  { sr: "diplomat",     ru: "дипломат",         category: "jobs" },
  { sr: "frizer",       ru: "парикмахер",       category: "jobs" },
];

const CATEGORIES = {
  all:       "Все",
  greetings: "Приветствия",
  numbers:   "Числа",
  food:      "Еда и напитки",
  family:    "Семья",
  city:      "Город",
  travel:    "Путешествия",
  weather:   "Погода",
  clothes:   "Одежда",
  home:      "Дом",
  verbs:     "Глаголы",
  jobs:      "Профессии",
};
